"""empty message

Revision ID: 676579541796
Revises: fa2fdcb564a1
Create Date: 2022-05-30 15:16:00.998771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676579541796'
down_revision = 'fa2fdcb564a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marvel_hero', 'abilities',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marvel_hero', 'abilities',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
